import LocalizedStrings from "react-native-localization";

export const translations = new LocalizedStrings({
  "tr-TR": {
    noLocationService: "Lokasyon Servisi Kapalı",
    logout: "Çıkış",
    yes: "Evet",
    no: "Hayır",
    cancel: "İptal",
    areYouSure: "Emin misiniz?",
    logoutDesc: "Çıkış yapmak üzeresiniz onaylıyor musunuz?",
    noInternet: "İnternet Bağlantısı Yok",
    settings: "Ayarlar",
    appearance: "Görünüm",
    language: "Dil",
    darkMode: "Koyu Mod",
    lightMode: "Açık Mod",
    english: "İngilizce",
    turkish: "Türkçe",
    vietnamese: "Vietnamca",
    chinese: "Çince",
    home: "Ana Sayfa",
    guide: "Rehber",
    units: "Birimler",
    traits: "Özellikler",
    items: "Eşyalar",
    upgrades: "Yükseltmeler",
    augments: "Artırımlar",
  },
  en: {
    noLocationService: "Location Service Not Available",
    logout: "Logout",
    yes: "Yes",
    no: "No",
    cancel: "Cancel",
    areYouSure: "Are you sure?",
    logoutDesc: "You are about to log out, confirm?",
    noInternet: "No Internet Connection",
    settings: "Settings",
    appearance: "Appearance",
    language: "Language",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    english: "English",
    turkish: "Turkish",
    vietnamese: "Vietnamese",
    chinese: "Chinese",
    home: "Home",
    guide: "Guide",
    settings: "Settings",
    units: "Units",
    traits: "Traits",
    items: "Items",
    upgrades: "Upgrades",
    augments: "Augments",
  },
  vi: {
    noLocationService: "Dịch vụ vị trí không khả dụng",
    logout: "Đăng xuất",
    yes: "Có",
    no: "Không",
    cancel: "Hủy",
    areYouSure: "Bạn có chắc chắn?",
    logoutDesc: "Bạn sắp đăng xuất, xác nhận?",
    noInternet: "Không có kết nối Internet",
    settings: "Cài đặt",
    appearance: "Giao diện",
    language: "Ngôn ngữ",
    darkMode: "Chế độ tối",
    lightMode: "Chế độ sáng",
    english: "Tiếng Anh",
    turkish: "Tiếng Thổ Nhĩ Kỳ",
    vietnamese: "Tiếng Việt",
    chinese: "Tiếng Trung",
    home: "Trang chủ",
    guide: "Hướng dẫn",
    settings: "Cài đặt",
    units: "Tướng",
    traits: "Tộc/Hệ",
    items: "Trang bị",
    upgrades: "Nâng cấp",
    augments: "Thức tỉnh",
  },
  "zh-CN": {
    noLocationService: "位置服务不可用",
    logout: "登出",
    yes: "是",
    no: "否",
    cancel: "取消",
    areYouSure: "您确定吗？",
    logoutDesc: "您即将登出，确认吗？",
    noInternet: "无网络连接",
    settings: "设置",
    appearance: "外观",
    language: "语言",
    darkMode: "深色模式",
    lightMode: "浅色模式",
    english: "英语",
    turkish: "土耳其语",
    vietnamese: "越南语",
    chinese: "中文",
    home: "首页",
    guide: "指南",
    settings: "设置",
    units: "单位",
    traits: "特质",
    items: "物品",
    upgrades: "升级",
    augments: "增强",
  },
});

// ? Set the language manually
// translations.setLanguage("tr");
