import LocalizedStrings from "react-native-localization";

export const translations = new LocalizedStrings({
  "tr-TR": {
    noLocationService: "Lokasyon Servisi Kapalı",
    logout: "Çıkış",
    yes: "Evet",
    no: "Hayır",
    cancel: "İptal",
    areYouSure: "Emin misiniz?",
    logoutDesc: "Çıkış yapmak üzeresiniz onaylıyor musunuz?",
    noInternet: "İnternet Bağlantısı Yok",
    settings: "Ayarlar",
    appearance: "Görünüm",
    language: "Dil",
    darkMode: "Koyu Mod",
    lightMode: "Açık Mod",
    english: "İngilizce",
    turkish: "Türkçe",
    vietnamese: "Vietnamca",
    chinese: "Çince",
    home: "Ana Sayfa",
    guide: "Rehber",
    units: "Birimler",
    traits: "Özellikler",
    items: "Eşyalar",
    upgrades: "Yükseltmeler",
    augments: "Artırımlar",
    loadingUnit: "Tướng yükleniyor...",
    errorLoadingUnit: "Tướng yüklenirken hata",
    somethingWentWrong: "Bir şeyler yanlış gitti",
    retry: "Yeniden Dene",
    health: "Can",
    attackSpeed: "Saldırı Hızı",
    attackDamage: "Saldırı Hasarı",
    armor: "Zırh",
    dps: "DPS",
    magicResist: "Büyü Direnci",
    range: "Menzil",
    mana: "Mana",
    ability: "Yetenek",
    level: "Seviye",
    suggestedItems: "Önerilen Eşyalar",
    abilityCanCrit: "Yetenek kritik vurabilir.",
    unlock: "Aç",
    loadingComposition: "Kompozisyon yükleniyor...",
    errorLoadingComposition: "Kompozisyon yüklenirken hata",
    earlyGame: "Oyun Başlangıcı",
    midGame: "Oyun Ortası",
    lateGame: "Oyun Sonu",
    traitsSection: "Özellikler",
    carryUnitsSection: "Ana Birimler ve Eşyalar",
    loadingTrait: "Özellik yükleniyor...",
    errorLoadingTrait: "Özellik yüklenirken hata",
    traitEffects: "Özellik Etkileri",
    description: "Açıklama",
    units: "Birimler",
    errorLoadingUnits: "Birimler yüklenirken hata",
    noUnitsFound: "Bu özelliğe sahip birim bulunamadı",
    noCompositionsFound: "Kompozisyon bulunamadı",
    welcomeToTftBuddy: "TFTBuddy'ye Hoş Geldiniz",
    loadingCompositions: "Kompozisyonlar yükleniyor...",
    errorLoadingCompositions: "Kompozisyonlar yüklenirken hata",
    compositionsSection: "Kompozisyonlar",
    loadingUnits: "Birimler yükleniyor...",
    errorLoadingUnitsTab: "Birimler yüklenirken hata",
    noUnitsFoundTab: "Birim bulunamadı",
    noUnitsFoundWithFilters: "Filtrelerinize uygun birim bulunamadı",
    noMoreUnitsToLoad: "Yüklenecek daha fazla birim yok",
    loadingItems: "Eşyalar yükleniyor...",
    errorLoadingItems: "Eşyalar yüklenirken hata",
    noItemsFound: "Eşya bulunamadı",
    noMoreItemsToLoad: "Yüklenecek daha fazla eşya yok",
    loadingTraits: "Özellikler yükleniyor...",
    errorLoadingTraits: "Özellikler yüklenirken hata",
    noTraitsFound: "Özellik bulunamadı",
    noMoreTraitsToLoad: "Yüklenecek daha fazla özellik yok",
    loadingChampions: "Şampiyonlar yükleniyor...",
    errorLoadingChampions: "Şampiyonlar yüklenirken hata",
    errorLoadingChampion: "Şampiyon yüklenirken hata",
    noChampionsFound: "Şampiyon bulunamadı",
    noMoreChampionsToLoad: "Yüklenecek daha fazla şampiyon yok",
    loadingAugments: "Artırımlar yükleniyor...",
    errorLoadingAugments: "Artırımlar yüklenirken hata",
    noAugmentsFound: "Artırım bulunamadı",
    noAugmentsFoundWithFilters: "Filtrelerinize uygun artırım bulunamadı",
    noMoreAugmentsToLoad: "Yüklenecek daha fazla artırım yok",
    loadingItem: "Eşya yükleniyor...",
    errorLoadingItem: "Eşya yüklenirken hata",
    cost: "Maliyet",
    stage: "Aşama",
    tier: "Seviye",
    sortBy: "Sırala",
    sortOrder: "Sıralama Düzeni",
    search: "Ara",
    filter: "Filtre",
    filterByUnits: "Lọc theo tướng",
    unique: "Benzersiz",
    trait: "Özellik",
    noMoreToLoad: "Yüklenecek daha fazla öğe yok",
    clearAll: "Tümünü Temizle",
    searchUnitsPlaceholder: "Birim adına göre ara...",
    role: "Rol",
    all: "Tümü",
    origin: "Köken",
    class: "Sınıf",
    tier1: "Tier 1",
    tier2: "Tier 2",
    tier3: "Tier 3",
    noTier: "Tier Yok",
    unknown: "Bilinmeyen",
    loadingUnits: "Birimler yükleniyor...",
    unitsSelected: "birim seçildi",
    clear: "Temizle",
    noUnitsAvailable: "Mevcut birim yok",
    silverI: "Gümüş I",
    goldII: "Altın II",
    prismaticIII: "Prismatik III",
  },
  en: {
    noLocationService: "Location Service Not Available",
    logout: "Logout",
    yes: "Yes",
    no: "No",
    cancel: "Cancel",
    areYouSure: "Are you sure?",
    logoutDesc: "You are about to log out, confirm?",
    noInternet: "No Internet Connection",
    settings: "Settings",
    appearance: "Appearance",
    language: "Language",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    english: "English",
    turkish: "Turkish",
    vietnamese: "Vietnamese",
    chinese: "Chinese",
    home: "Home",
    guide: "Guide",
    settings: "Settings",
    units: "Units",
    traits: "Traits",
    items: "Items",
    upgrades: "Upgrades",
    augments: "Augments",
    loadingUnit: "Loading unit...",
    errorLoadingUnit: "Error loading unit",
    somethingWentWrong: "Something went wrong",
    retry: "Retry",
    health: "Health",
    attackSpeed: "Attack Speed",
    attackDamage: "Attack Damage",
    armor: "Armor",
    dps: "DPS",
    magicResist: "Magic Resist",
    range: "Range",
    mana: "Mana",
    ability: "Ability",
    level: "Level",
    suggestedItems: "Suggested Items",
    abilityCanCrit: "Ability can crit.",
    unlock: "Unlock",
    loadingComposition: "Loading composition...",
    errorLoadingComposition: "Error loading composition",
    earlyGame: "Early Game",
    midGame: "Mid Game",
    lateGame: "Late Game",
    traitsSection: "Traits",
    carryUnitsSection: "Carry Units and Items",
    loadingTrait: "Loading trait...",
    errorLoadingTrait: "Error loading trait",
    traitEffects: "Trait Effects",
    description: "Description",
    units: "Units",
    errorLoadingUnits: "Error loading units",
    noUnitsFound: "No units found with this trait",
    noCompositionsFound: "No compositions found",
    welcomeToTftBuddy: "Welcome to TFTBuddy",
    loadingCompositions: "Loading compositions...",
    errorLoadingCompositions: "Error loading compositions",
    compositionsSection: "Compositions",
    loadingUnits: "Loading units...",
    errorLoadingUnitsTab: "Error loading units",
    noUnitsFoundTab: "No units found",
    noUnitsFoundWithFilters: "No units found matching your filters",
    noMoreUnitsToLoad: "No more units to load",
    loadingItems: "Loading items...",
    errorLoadingItems: "Error loading items",
    noItemsFound: "No items found",
    noMoreItemsToLoad: "No more items to load",
    loadingTraits: "Loading traits...",
    errorLoadingTraits: "Error loading traits",
    noTraitsFound: "No traits found",
    noMoreTraitsToLoad: "No more traits to load",
    loadingChampions: "Loading champions...",
    errorLoadingChampions: "Error loading champions",
    errorLoadingChampion: "Error loading champion",
    noChampionsFound: "No champions found",
    noMoreChampionsToLoad: "No more champions to load",
    loadingAugments: "Loading augments...",
    errorLoadingAugments: "Error loading augments",
    noAugmentsFound: "No augments found",
    noAugmentsFoundWithFilters: "No augments found matching your filters",
    noMoreAugmentsToLoad: "No more augments to load",
    loadingItem: "Loading item...",
    errorLoadingItem: "Error loading item",
    cost: "Cost",
    stage: "Stage",
    tier: "Tier",
    sortBy: "Sort By",
    sortOrder: "Sort Order",
    search: "Search",
    filter: "Filter",
    filterByUnits: "Filter by units",
    unique: "Unique",
    trait: "Trait",
    noMoreToLoad: "No more items to load",
    clearAll: "Clear All",
    searchUnitsPlaceholder: "Search units by name...",
    role: "Role",
    all: "All",
    origin: "Origin",
    class: "Class",
    tier1: "Tier 1",
    tier2: "Tier 2",
    tier3: "Tier 3",
    noTier: "No Tier",
    unknown: "Unknown",
    loadingUnits: "Loading units...",
    unitsSelected: "units selected",
    clear: "Clear",
    noUnitsAvailable: "No units available",
    silverI: "Silver I",
    goldII: "Gold II",
    prismaticIII: "Prismatic III",
  },
  vi: {
    noLocationService: "Dịch vụ vị trí không khả dụng",
    logout: "Đăng xuất",
    yes: "Có",
    no: "Không",
    cancel: "Hủy",
    areYouSure: "Bạn có chắc chắn?",
    logoutDesc: "Bạn sắp đăng xuất, xác nhận?",
    noInternet: "Không có kết nối Internet",
    settings: "Cài đặt",
    appearance: "Giao diện",
    language: "Ngôn ngữ",
    darkMode: "Chế độ tối",
    lightMode: "Chế độ sáng",
    english: "Tiếng Anh",
    turkish: "Tiếng Thổ Nhĩ Kỳ",
    vietnamese: "Tiếng Việt",
    chinese: "Tiếng Trung",
    home: "Trang chủ",
    guide: "Hướng dẫn",
    settings: "Cài đặt",
    units: "Tướng",
    traits: "Tộc/Hệ",
    items: "Trang bị",
    upgrades: "Nâng cấp",
    augments: "Nâng cấp",
    loadingUnit: "Đang tải tướng...",
    errorLoadingUnit: "Lỗi tải tướng",
    somethingWentWrong: "Đã xảy ra lỗi",
    retry: "Thử lại",
    health: "Máu",
    attackSpeed: "Tốc Độ Đánh",
    attackDamage: "Sức Mạnh Công Kích",
    armor: "Giáp",
    dps: "DPS",
    magicResist: "Kháng Phép",
    range: "Tầm Đánh",
    mana: "Mana",
    ability: "Kỹ Năng",
    level: "Cấp độ",
    suggestedItems: "Đề xuất Trang bị",
    abilityCanCrit: "Kỹ năng có thể gây chí mạng.",
    unlock: "Mở khóa",
    loadingComposition: "Đang tải đội hình...",
    errorLoadingComposition: "Lỗi tải đội hình",
    earlyGame: "Đầu trận",
    midGame: "Giữa trận",
    lateGame: "Cuối trận",
    traitsSection: "Tộc/Hệ",
    carryUnitsSection: "Tướng và Trang bị Chủ chốt",
    loadingTrait: "Đang tải tộc/hệ...",
    errorLoadingTrait: "Lỗi tải tộc/hệ",
    traitEffects: "Hiệu ứng Trait",
    description: "Mô tả",
    units: "Tướng",
    errorLoadingUnits: "Lỗi tải tướng",
    noUnitsFound: "Không tìm thấy tướng nào có tộc/hệ này",
    noCompositionsFound: "Không tìm thấy đội hình nào",
    welcomeToTftBuddy: "Chào mừng đến với TFTBuddy",
    loadingCompositions: "Đang tải đội hình...",
    errorLoadingCompositions: "Lỗi tải đội hình",
    compositionsSection: "Đội hình",
    loadingUnits: "Đang tải tướng...",
    errorLoadingUnitsTab: "Lỗi tải tướng",
    noUnitsFoundTab: "Không tìm thấy tướng nào",
    noUnitsFoundWithFilters: "Không tìm thấy tướng nào phù hợp với bộ lọc",
    noMoreUnitsToLoad: "Không còn tướng nào để tải",
    loadingItems: "Đang tải trang bị...",
    errorLoadingItems: "Lỗi tải trang bị",
    noItemsFound: "Không tìm thấy trang bị nào",
    noMoreItemsToLoad: "Không còn trang bị nào để tải",
    loadingTraits: "Đang tải tộc/hệ...",
    errorLoadingTraits: "Lỗi tải tộc/hệ",
    noTraitsFound: "Không tìm thấy tộc/hệ nào",
    noMoreTraitsToLoad: "Không còn tộc/hệ nào để tải",
    loadingChampions: "Đang tải tướng...",
    errorLoadingChampions: "Lỗi tải tướng",
    errorLoadingChampion: "Lỗi tải tướng",
    noChampionsFound: "Không tìm thấy tướng nào",
    noMoreChampionsToLoad: "Không còn tướng nào để tải",
    loadingAugments: "Đang tải nâng cấp...",
    errorLoadingAugments: "Lỗi tải nâng cấp",
    noAugmentsFound: "Không tìm thấy nâng cấp nào",
    noAugmentsFoundWithFilters: "Không tìm thấy nâng cấp nào phù hợp với bộ lọc",
    noMoreAugmentsToLoad: "Không còn nâng cấp nào để tải",
    loadingItem: "Đang tải trang bị...",
    errorLoadingItem: "Lỗi tải trang bị",
    cost: "Giá",
    stage: "Giai đoạn",
    tier: "Cấp độ",
    sortBy: "Sắp xếp theo",
    sortOrder: "Thứ tự sắp xếp",
    search: "Tìm kiếm",
    filter: "Lọc",
    filterByUnits: "Lọc theo tướng",
    unique: "Độc nhất",
    trait: "Tộc/Hệ",
    noMoreToLoad: "Không còn mục nào để tải",
    clearAll: "Xóa tất cả",
    searchUnitsPlaceholder: "Tìm kiếm tướng theo tên...",
    role: "Vai trò",
    all: "Tất cả",
    origin: "Tộc",
    class: "Hệ",
    tier1: "Tier 1",
    tier2: "Tier 2",
    tier3: "Tier 3",
    noTier: "Không có Tier",
    unknown: "Không xác định",
    loadingUnits: "Đang tải tướng...",
    unitsSelected: "tướng đã chọn",
    clear: "Xóa",
    noUnitsAvailable: "Không có tướng nào",
    silverI: "Bạc I",
    goldII: "Vàng II",
    prismaticIII: "Kim Cương III",
  },
  "zh-CN": {
    noLocationService: "位置服务不可用",
    logout: "登出",
    yes: "是",
    no: "否",
    cancel: "取消",
    areYouSure: "您确定吗？",
    logoutDesc: "您即将登出，确认吗？",
    noInternet: "无网络连接",
    settings: "设置",
    appearance: "外观",
    language: "语言",
    darkMode: "深色模式",
    lightMode: "浅色模式",
    english: "英语",
    turkish: "土耳其语",
    vietnamese: "越南语",
    chinese: "中文",
    home: "首页",
    guide: "指南",
    settings: "设置",
    units: "单位",
    traits: "特质",
    items: "物品",
    upgrades: "升级",
    augments: "增强",
    loadingUnit: "加载单位中...",
    errorLoadingUnit: "加载单位错误",
    somethingWentWrong: "出错了",
    retry: "重试",
    health: "生命值",
    attackSpeed: "攻击速度",
    attackDamage: "攻击力",
    armor: "护甲",
    dps: "每秒伤害",
    magicResist: "魔法抗性",
    range: "攻击范围",
    mana: "法力值",
    ability: "技能",
    level: "等级",
    suggestedItems: "推荐装备",
    abilityCanCrit: "技能可以暴击。",
    unlock: "解锁",
    loadingComposition: "加载阵容中...",
    errorLoadingComposition: "加载阵容错误",
    earlyGame: "前期",
    midGame: "中期",
    lateGame: "后期",
    traitsSection: "特质",
    carryUnitsSection: "核心单位和物品",
    loadingTrait: "加载特质中...",
    errorLoadingTrait: "加载特质错误",
    traitEffects: "特质效果",
    description: "描述",
    units: "单位",
    errorLoadingUnits: "加载单位错误",
    noUnitsFound: "未找到具有此特质的单位",
    noCompositionsFound: "未找到阵容",
    welcomeToTftBuddy: "欢迎使用 TFTBuddy",
    loadingCompositions: "加载阵容中...",
    errorLoadingCompositions: "加载阵容错误",
    compositionsSection: "阵容",
    loadingUnits: "加载单位中...",
    errorLoadingUnitsTab: "加载单位错误",
    noUnitsFoundTab: "未找到单位",
    noUnitsFoundWithFilters: "未找到符合筛选条件的单位",
    noMoreUnitsToLoad: "没有更多单位可加载",
    loadingItems: "加载物品中...",
    errorLoadingItems: "加载物品错误",
    noItemsFound: "未找到物品",
    noMoreItemsToLoad: "没有更多物品可加载",
    loadingTraits: "加载特质中...",
    errorLoadingTraits: "加载特质错误",
    noTraitsFound: "未找到特质",
    noMoreTraitsToLoad: "没有更多特质可加载",
    loadingChampions: "加载单位中...",
    errorLoadingChampions: "加载单位错误",
    errorLoadingChampion: "加载单位错误",
    noChampionsFound: "未找到单位",
    noMoreChampionsToLoad: "没有更多单位可加载",
    loadingAugments: "加载增强中...",
    errorLoadingAugments: "加载增强错误",
    noAugmentsFound: "未找到增强",
    noAugmentsFoundWithFilters: "未找到符合筛选条件的增强",
    noMoreAugmentsToLoad: "没有更多增强可加载",
    loadingItem: "加载物品中...",
    errorLoadingItem: "加载物品错误",
    cost: "费用",
    stage: "阶段",
    tier: "等级",
    sortBy: "排序方式",
    sortOrder: "排序顺序",
    search: "搜索",
    filter: "筛选",
    filterByUnits: "按单位筛选",
    unique: "独特",
    trait: "特质",
    noMoreToLoad: "没有更多项目可加载",
    clearAll: "清除全部",
    searchUnitsPlaceholder: "按名称搜索单位...",
    role: "角色",
    all: "全部",
    origin: "起源",
    class: "职业",
    tier1: "等级 1",
    tier2: "等级 2",
    tier3: "等级 3",
    noTier: "无等级",
    unknown: "未知",
    loadingUnits: "加载单位中...",
    unitsSelected: "个单位已选择",
    clear: "清除",
    noUnitsAvailable: "无可用单位",
    silverI: "白银 I",
    goldII: "黄金 II",
    prismaticIII: "棱彩 III",
  },
});

// ? Set the language manually
// translations.setLanguage("tr");
