import type { ExtendedTheme } from "@react-navigation/native";
import { DefaultTheme } from "@react-navigation/native";

export const palette = {
  primary: "#FF8C00",
  secondary: "#ff6a00",
  background: "#f6f8fa",
  white: "#fff",
  black: "#101214",
  button: "#1c1e21",
  shadow: "#757575",
  text: "#30363b",
  borderColor: "#d0d7de",
  borderColorDark: "#333942",
  placeholder: "#a1a1a1",
  danger: "#D0021B", // hex để nối alpha (vd: danger + '20') hoạt động cho badge Tộc/Hệ
  title: "rgb(102, 102, 102)",
  separator: "rgb(194, 194, 195)",
  highlight: "rgb(199, 198, 203)",
  blackOverlay: "rgba(0,0,0,0.6)",
  iconWhite: "#fff",
  iconBlack: "#101214",
  dynamicWhite: "#fff",
  dynamicBlack: "#1c1e21",
  dynamicBackground: "#fff",
  transparent: "transparent",
  calpyse: "#2b7488",
  green: "#008000",
  /** Nền xám dùng chung cho hexagon (card, detail, guide...) */
  hexagonBg: "#222222",
};

export const LightTheme: ExtendedTheme = {
  dark: false,
  colors: {
    ...DefaultTheme.colors,
    background: '#000000',
    card: '#1a1a1a',
    text: '#101214',
    border: '#2a2a2a',
    notification: palette.primary,
    primary: palette.primary,
    secondary: palette.secondary,
    white: '#fff',
    black: '#101214',
    button: '#1c1e21',
    shadow: '#757575',
    borderColor: '#2a2a2a',
    borderColorDark: '#333942',
    placeholder: '#a1a1a1',
    danger: palette.danger,
    title: '#30363b',
    separator: '#2a2a2a',
    highlight: '#e1e4e8',
    blackOverlay: 'rgba(0,0,0,0.6)',
    iconWhite: '#fff',
    iconBlack: '#101214',
    dynamicWhite: '#fff',
    dynamicBlack: '#1c1e21',
    dynamicBackground: '#ffffff',
    transparent: 'transparent',
    calpyse: palette.calpyse,
    green: palette.green,
    hexagonBg: palette.hexagonBg,
  },
};

export const DarkTheme: ExtendedTheme = {
  dark: true,
  colors: {
    ...DefaultTheme.colors,
    background: '#000000',
    card: '#1a1a1a',
    text: '#ffffff',
    border: '#2a2a2a',
    notification: palette.primary,
    primary: palette.primary,
    secondary: palette.secondary,
    white: '#fff',
    black: '#1a1d29',
    button: '#252836',
    shadow: '#000000',
    borderColor: '#2a2a2a',
    borderColorDark: '#2a2a2a',
    placeholder: '#8e8e93',
    danger: palette.danger,
    title: '#ffffff',
    separator: '#2a2a2a',
    highlight: '#3a3d4a',
    blackOverlay: 'rgba(0,0,0,0.6)',
    iconWhite: '#fff',
    iconBlack: '#fff',
    dynamicWhite: '#fff',
    dynamicBlack: '#252836',
    dynamicBackground: '#252836',
    transparent: 'transparent',
    calpyse: palette.calpyse,
    tabBar: '#1a1d29',
    foreground: '#ffffff',
    green: palette.green,
    hexagonBg: palette.hexagonBg,
  },
};
